version: '3.8'

services:
  # The Local Redis Broker
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # The FastAPI Web Server
  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

  # The Celery Background Worker
  celery_worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis
      - api
